lzr/mblog/mainsite/urls.py
__author__ = 'YuLongZ'
#coding:utf-8
from django.conf.urls import url
from .views import search
#from haystack.views import SearchView


app_name='mainstite'
urlpatterns=[
    # SearchView()视图函数，默认使用的HTML模板路径为templates/search/search.html
    url(r'search/$',search, name='elastic_search'),
]

lzr/mblog/mblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from mainsite.views import homepage_2,showpost,login,logout,register,demo
from haystack.views import SearchView

urlpatterns = [
    url(r'^$',homepage_2),
    path('admin/', admin.site.urls),
    url(r'^post/(\w+)$',showpost),
    #url(r'search/$',include('haystack.urls'),)
    path('',include('mainsite.urls',namespace='mainsite')),
    path('login/', login),
    path('logout/', logout),
    path('register/', register),
    # path('dome',demo)
    path('demo',demo)
]

lzr/mblog/mainsite/models.py
#coding:utf-8
from django.db import models
from django.utils import timezone
# Create your models here.

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    slug= models.CharField(max_length=200)
    body= models.TextField ()
    pub_date = models.DateTimeField (default=timezone.now)

    class Meta:
          ordering =('-pub_date',)

    def __str__(self):
          return self.title

#鉴权mode
class Permission(models.Model):
    class Meta:
        #权限信息，这里定义的权限的名字，后面是描述信息，描述信息是在django admin中显示权限用的
        permissions = (
            ('views_slg_users_tem', '查看玩家管理'),
            ('views_slg_alliance_tem', '查看联盟管理'),
            ('views_slg_mail_notice_tem', '查看公告邮件'),
            ('views_slg_order_tem', '查看订单系统'),
            ('views_slg_reward_tem', '查看礼包奖励'),
            ('views_slg_service_reply_tem', '查看客服反馈'),
            ('views_slg_user_log_tem', '查看玩家日志'),
            ('views_slg_server_tem', '查看服务器管理'),
            ('views_slg_manager_tem', '查看管理员管理'),
        )

#搜索接口样例mode---haystack no
class ArticlePost(models.Model):

    #author = models.ForeignKey(User, related_name='article')     #考究
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    #column = models.ForeignKey(ArticleColumn, related_name='article_column')
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    updated = models.DateTimeField(auto_now_add=True)
    # media/%Y%m%d/为图片的真实放置路径，因为settings中已经配置了MEDIA_ROOT为media文件夹
    avatar = models.ImageField(upload_to='%Y%m%d/', blank=True)

from django.db import models

class User(models.Model):
	username = models.CharField(verbose_name='用户名', max_length=40, unique=True)
	password = models.CharField(verbose_name='口令', max_length=256)

	def __str__(self):
		return self.username

lzr/mblog/mainsite/views.py
#coding:utf-8
from django.shortcuts import render
from django.http import  HttpResponse
from django.shortcuts import redirect
from django.template.loader import get_template
from datetime import datetime
from .models import Post,User
from .search_indexes import do_search
from functools import wraps
import json
# Create your views here.

def check_login(func):
    @wraps(func)     #是wraps一个可以确保调用装饰器时不会改变原函数属性
    def inner(request, *arg, **kwargs):
        if request.session.get('is_login', None):
            return func(request, *arg, **kwargs)
        return redirect('/login/')
    return inner

@check_login
def homepage_2(request):
    template = get_template("index.html")
    posts = Post.objects.all()
    now = datetime.now()
    user = request.session['username']
    html = template.render(locals())
    return HttpResponse(html)

def showpost(request,slug):
    request=request
    slug=slug
    template = get_template("post.html")
    try:
        post = Post.objects.get(slug=slug)
        if post != None:
            html = template.render(locals())
            return HttpResponse(html)
    except:
        return redirect('/')

def search(request):
    request.encoding='utf-8'
    if 'q' in request.GET and request.GET['q']:
        message=do_search('title',request.GET['q'])
        print(type(message),message)
        message.setdefault('user',request.session['username'])
    else:
        #message = 'normal falid'
        return render(request,'index.html',{'mess':"不允许传空"})
    return render(request,'search.html',message)

def login(request):
    if request.session.get('is_login', None):  # 检查是否已登录
        return redirect('/') #跳转到主页
    if request.method == 'POST':  # 如果有提交表单
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '').strip()
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return render(request, 'login.html', {'mess': '用户不存在'})
        else:
            if password == user.password:
                request.session['is_login'] = True  # 标记已登录
                request.session['user_id'] = user.id
                request.session['username'] = username
                return redirect('/')
            else:
                return render(request, 'login.html', {'mess': '密码输入错误'})
    return render(request, 'login.html')

def logout(request):
    if request.session.get('is_login', None):
        request.session.flush()
    return redirect('/login/')


def register(request):
    if request.session.get('is_login', None):
        request.session.flush()
    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '').strip()
        re_password = request.POST.get('re_password', '').strip()
        if password == re_password:
            try:
                User.objects.get(username=username)
            except User.DoesNotExist:
                new_user = User(username=username, password=password)
                new_user.save()
                return render(request, 'register.html', {'mess': '用户注册成功'})
            else:
                return render(request, 'register.html', {'mess': '该用户已被注册'})
        else:
            return render(request, 'register.html', {'mess': '两次密码输入不一致'})
    return render(request, 'register.html')

def demo(request):
    fa = {"1":1,"2":2}
    return HttpResponse(str(fa))

lzr/mblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        {% block title %} {% endblock %}
    </title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- 引入 Bootstrap -->
    <link href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <!-- 包括所有已编译的插件 -->
    {% load static %}
    <script src={% static 'js/bootstrap.min.js' %}></script>
	<script src={% static 'js/echarts.js' %}></script>
<script> 
    $('input[id=paper_file]').change(function() {
        $("#rst_message").remove();
        $('#photoCover').val($(this).val().replace("test", ""));
    });
</script>
 </head>
<body>
    <div class="container">
       <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row" style="margin-top:10px;">
            <input id="paper_file" name="paper_file" type="file" style="display:none">
            <div class="col-md-2 col-md-offset-4 col-lg-2 col-lg-offset-4" style="padding-top:7px;text-align:right;"><label>选择导入的班级分数Excel</label></div>
            <div class="col-md-4 col-lg-4">
                <input id="photoCover" class="form-control" type="text" style="height:30px;"></div>
			<div class="col-md-1 col-lg-1">
                <a class="btn btn-primary btn-sm" onclick="$('input[id=paper_file]').click();"><i class="icon-folder-open"></i>&nbsp;&nbsp;浏览文件</a>
			</div>
			<div class="col-md-1 col-lg-1">
				<button type="submit" name="Create" id="btn_import_paper" class="btn btn-primary btn-sm" style="margin-bottom:5px;margin-right:8px;"><i class="icon-upload-alt"></i>&nbsp;&nbsp;导入</button>
            </div>
		</div>
       </form>
	 </div>
{% include 'header.html' %}
{% block headmessage %} {% endblock %}
{% block content %} {% endblock %}
{% include 'footer.html' %}


</body>
</html>

lzr/mblog/templates/footer.html
{% block footer %}
这里是底部格式
{% endblock %}

lzr/mblog/templates/header.html
<!DOCTYPE html>
<div class='well'>
<h1>这里是通用的header头部 存放跳转应用 用户登录信息 用户：{{ user }} <a href="/logout/">注销</a></h1>
<li>
            <form action="{% url 'mainsite:elastic_search' %}" method="get">
                <input type="text" name="q" placeholder="请输入关键字">
                <input type="submit" id="search" value="搜索">
            </form>		
</li>
</div>

lzr/mblog/templates/index.html
{% extends 'base.html' %}
{% block title %} zero的创作空间 {% endblock %}
{% block headmessage %} 
<h3>这里是自动化测试功能主体</h3> 
<div id='hani' class='col-md-9' style='height:300px;'>
   <p id="demo">动态刷新数据</p>
   <button type="button" onclick="loadDoc()"> 检查节目单情况 </button>
</div>
<div class="container" >
   <div class='row'>
       <div id='main' class='col-md-9' style='height:200px;'>
	
       <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));
 
        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '第一个 ECharts 实例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };
 
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
   </div>
	   <div class='col-md-3'>
	      <div class='row'>
		    <div class='col-md-12' style='height:100px;background-color:#dedef8'>
			<p>这里接入学生信息</p>
			</div>
			<div class='col-md-12' style='height:100px;background-color:#dedef8'>
			<p>这里接入信息通知</p>
			</div>
		  </div>
	   </div>
   </div>
</div>
<script>
function loadDoc() {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("demo").innerHTML = this.responseText;
    }
  };
   xhttp.open("GET", "demo", true);
   xhttp.send();
}
</script>
{% endblock %}

lzr/mblog/templates/login.html
<!-- login.html -->

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>登录</title>
</head>
<body>
	<div class="login">
		<h2>欢迎登录！</h2>
		<br/>
		<form action="/login/" method="post">
			{% csrf_token %}
	        <p>账号：
	      		<input type="text" name="username" value="">
	    	</p>
	        <p>密码：
				<input type="password" name="password">
			</p>
			<br/>
			<input type="submit" value="登录">
			<button type="button" onclick="window.location.href='/register/'">注册</button>
		</form>
		<div>{{ mess }}</div>

	</div>
</body>
</html>

lzr/mblog/templates/register.html
<!-- register.html -->

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>用户注册</title>
</head>
<body>
	<div>
		<h2>请输入待注册的用户信息</h2>
		<form action="/register/" method="post">
			{% csrf_token %}
			<p>账号：
		  		<input type="text" name="username">
			</p>
			<p>密码：
				<input type="password" name="password">
			</p>
			<p>再次输入：
				<input type="password" name="re_password">
			</p>
			<br/>
			<input type="submit" value="注册用户">
		</form>
	</div>
	<a href="/login/">返回登录</a>
	<div>{{ mess }}</div>
</body>
</html>

lzr/mblog/templates/search.html
{% extends 'base.html' %} 
{% block title %}搜索结果{% endblock %}
{% block content %}
    <div class="col-md-9">
    <div class="row text-center vertical-middle-sm">
        <h1>搜索结果</h1>
		{% if  imge_url %}
		{{ imge_url }}
		   {% load static %}
		   <img src={% static  imge_url  %} class="img-responsive" alt="响应式图像">
		{% else %}
		<h1> 搜索为空 </h1>
		{% endif %}
    </div>
{% endblock %}

lzr/mblog/templates/user_index.html
    <div id="permissionManageDiv" style="margin-left: 10px; display: none;">
        <div>
            <h4 style="margin-top: 15px;">选择用户</h4>
            <hr style="margin-top: 5px;" />
            <select name="usernamePermission" id="usernamePermission" class="selectpicker" data-live-search="true">
                {% for user in users %}
                    <option value="{{ user.username }}">{{ user.username }}</option>
                {% endfor %}
            </select>
            <hr />
        </div>

        <div>
            <h4 style="margin-top: 15px;">勾选权限</h4>
            <hr style="margin-top: 5px;" />
            <div style="margin-bottom: 10px;">
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">玩家管理</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="0" />
                    </span>
                </div>
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">联盟管理</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="1" />
                    </span>
                </div>
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">公告邮件</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="2" />
                    </span>
                </div>
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">订单系统</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="3" />
                    </span>
                </div>
                <div class="input-group input-group-lg" style="">
                    <span class="input-group-addon">礼包奖励</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="4" />
                    </span>
                </div>
            </div>

            <div>
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">客服反馈</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="5" />
                    </span>
                </div>
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">玩家日志</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="6" />
                    </span>
                </div>
                <div class="input-group input-group-lg" style="float: left; margin-right: 10px;">
                    <span class="input-group-addon">服务器管理</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="7" />
                    </span>
                </div>
                <div class="input-group input-group-lg">
                    <span class="input-group-addon">管理员管理</span>
                    <span class="input-group-addon">
                        <input type="checkbox" name="permissionList" value="8" />
                    </span>
                </div>
            </div>
        </div>
        <button type="button" id="changePermissionBtn" class="btn btn-default" style="width: 100px; margin-top: 15px;" data-toggle="modal" data-target="#alertTip" data-whatever="重置权限？" >提&nbsp;&nbsp;交</button>
    </div>